from __future__ import annotations

import csv
import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "pipeline-data"

# Input: current batch generated by scripts/generate-images.py
PINS_EXPORT_CSV = DATA_DIR / "pins-export.csv"

# Output: file that matches the Publer import format/structure
PINS_EXPORT_PUBLER_CSV = DATA_DIR / "pins-export-publer.csv"

CONTENT_TRACKER_FILE = DATA_DIR / "content-tracker.json"

SITE_URL = "https://www.daily-life-hacks.com"
PINS_IMG_BASE_URL = f"{SITE_URL}/images/pins"


def load_json(path: Path):
    import json

    return json.loads(path.read_text(encoding="utf-8"))


def get_board(slug: str, category: str) -> str:
    slug_lower = slug.lower()
    breakfast_keywords = ["breakfast", "smoothie", "oat", "snack", "granola", "yogurt", "morning"]
    if any(kw in slug_lower for kw in breakfast_keywords):
        return "Healthy Breakfast, Smoothies and Snacks"
    if category == "recipes":
        return "High Fiber Dinner and Gut Health Recipes"
    return "Gut Health Tips and Nutrition Charts"


def parse_slug_from_image_filename(image_filename: str) -> str:
    # Example: quick-20-minute-high-fiber-meals-for-busy-days_v1.jpg
    # We want: quick-20-minute-high-fiber-meals-for-busy-days
    name = os.path.basename(image_filename)
    if "_v" not in name:
        return name.rsplit(".", 1)[0]
    return name.split("_v", 1)[0]


def main() -> None:
    tracker = load_json(CONTENT_TRACKER_FILE)
    category_by_slug = {item.get("slug"): item.get("category", "nutrition") for item in tracker if item.get("slug")}

    # Read the current batch export (image_filename, pin_title, description, destination_url, board, alt_text)
    with open(PINS_EXPORT_CSV, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    out_rows = []
    for r in rows:
        image_filename = r["image_filename"]
        slug = parse_slug_from_image_filename(image_filename)
        category = category_by_slug.get(slug, "nutrition")

        out_rows.append(
            {
                "image_url": f"{PINS_IMG_BASE_URL}/{image_filename}",
                "pin_title": r["pin_title"],
                "description": r["description"],
                "destination_url": r["destination_url"],
                "board": get_board(slug, category),
                "alt_text": r["alt_text"],
            }
        )

    headers = ["image_url", "pin_title", "description", "destination_url", "board", "alt_text"]
    tmp_path = PINS_EXPORT_PUBLER_CSV.with_suffix(".csv.tmp")
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        writer.writerows(out_rows)

    os.replace(tmp_path, PINS_EXPORT_PUBLER_CSV)
    print(f"Rebuilt {PINS_EXPORT_PUBLER_CSV} rows={len(out_rows)}")


if __name__ == "__main__":
    main()

